#!/bin/bash
ls $LS_OPTIONS -a ~/.local/share/Trash/files/
read -p "Tout supprimer ? (o/n) " rep; [ "$rep" = "o" ] && /bin/rm -rf ~/.local/share/Trash/files/* ~/.local/share/Trash/files/.*  ~/.local/share/Trash/info/* >/dev/null 2>&1
